name: family_battle_app
description: Семейная битва — приложение для семейных челленджей.
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.4
  flutter_hooks: ^0.18.6

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  firebase_messaging: ^14.9.4

  # In-App Purchases
  in_app_purchase: ^3.2.1

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # Animations & graphics
  animations: ^2.0.11
  lottie: ^1.4.3
  cached_network_image: ^3.4.0
  image_picker: ^0.8.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/icons/first.png
    - assets/icons/photo.png
    - assets/icons/video.png
