name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flutter-channel: [ 'stable' ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: ${{ matrix.flutter-channel }}

      - name: Flutter pub get
        run: flutter pub get

      - name: Run unit tests
        run: flutter test

      - name: Run integration tests
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
        run: |
          flutter drive \
            --driver=integration_test/driver.dart \
            --target=integration_test/app_test.dart

      - name: Build APK
        if: success()
        run: flutter build apk --release

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: FamilyBattle-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
