- name: Run integration tests
-    uses: subosito/flutter-action@v2
-    with:
-      flutter-version: '3.29.3'
-    run: |
-      flutter drive \
-        --driver=integration_test/driver.dart \
-        --target=integration_test/app_test.dart
  +    # 1) Устанавливаем нужный Flutter (если не хотите повторно)
+- name: Ensure Flutter
+  uses: subosito/flutter-action@v2
+  with:
+    flutter-version: '3.29.3'
  +
  +    # 2) Запускаем тест-драйв
+- name: Run integration tests
+  run: |
  +    flutter drive \
  +      --driver=integration_test/driver.dart \
  +      --target=integration_test/app_test.dart
